# Generated by Django 4.0.5 on 2022-07-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=30)),
                ('subtítulo', models.CharField(max_length=30)),
                ('texto', models.CharField(max_length=1000)),
                ('imagen', models.CharField(max_length=1000)),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
