# Generated by Django 4.0.5 on 2022-06-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='comision',
        ),
    ]
