# Generated by Django 4.0.5 on 2022-07-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0002_blogcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcard',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
