# Generated by Django 4.0.5 on 2022-06-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0003_collares_comida_pipetas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collares',
            new_name='Collar',
        ),
        migrations.RenameModel(
            old_name='Pipetas',
            new_name='Pipeta',
        ),
        migrations.AlterModelOptions(
            name='collar',
            options={'verbose_name_plural': 'Collares'},
        ),
    ]
