# Generated by Django 4.0.5 on 2022-07-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0004_delete_collar_delete_comida_delete_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcard',
            name='texto',
            field=models.CharField(max_length=2000),
        ),
    ]
