# Generated by Django 4.0.5 on 2022-06-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0004_rename_collares_collar_rename_pipetas_pipeta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeta',
            name='tamaño',
        ),
    ]
