# Generated by Django 4.0.5 on 2022-07-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='/media/avatar/generica.jpg', null=True, upload_to='avatar/'),
        ),
    ]
